### ISSUE TITLE
Failed to execute 'replaceChild' on 'Node' in FormatJSONControl

### ISSUE THREAD

**Issue by bsobolewski-pirxon** [BenediktBergmann/PCF-Controls#105]
When using FormatJSONControl PCF Control I'm getting error
```
TypeError: Failed to execute 'replaceChild' on 'Node': parameter 2 is not of type 'Node'.
    at e.handleValue (https://org5c91f6b2.crm4.dynamics.com/%7b638457901850000196%7d/webresources/cc_BeBeControls.FormatJSONControl/bundle.js:2:4486)
    at e.init (https://org5c91f6b2.crm4.dynamics.com/%7b638457901850000196%7d/webresources/cc_BeBeControls.FormatJSONControl/bundle.js:2:2485)
    at https://content.powerapps.com/resource/uci-infra/scripts/19.f1989c21c8ef7b7cea9bc4f33b15da56.js:1:232245
    at t._measureLifecycleMethod (https://content.powerapps.com/resource/uci-infra/scripts/19.f1989c21c8ef7b7cea9bc4f33b15da56.js:1:229230)
    at t._initializeControl (https://content.powerapps.com/resource/uci-infra/scripts/19.f1989c21c8ef7b7cea9bc4f33b15da56.js:1:232182)
```

My control configuration
![Screenshot 2024-03-12 003646](https://github.com/BenediktBergmann/PCF-Controls/assets/163102022/f903701a-e45d-4cc7-9cba-f72a5f4b374b)

and field configuration
![Screenshot 2024-03-12 003719](https://github.com/BenediktBergmann/PCF-Controls/assets/163102022/f1e8b8f3-93a2-4680-aa14-01f4c30ff78a)

In interface it looks like this
![Screenshot 2024-03-12 075650](https://github.com/BenediktBergmann/PCF-Controls/assets/163102022/ccdb11df-bf46-4fd4-b4ef-cefe16655939)

![Screenshot 2024-03-12 075803](https://github.com/BenediktBergmann/PCF-Controls/assets/163102022/032cb471-f09a-4157-8a3b-6c48fc8064ff)

**Comment by clintwar** [comment]
Looks like they are not checking if syntax highlight is turned on and doing work only that needs to be done when that happens. Additionally they are trying to replace the first child node of the highlightedElement however it has no children. If you set a breakpoint and in console appendChild to this element then the control works. To be honest I am not really sure how this worked after the fixes they took in Commit https://github.com/BenediktBergmann/PCF-Controls/commit/251e0c4f9b7ec5d3db578ba9fa5eada416ef26ed. I don't really understand why they are messing with the unattached highlightedelement when syntax highlighting is not turned on.
